"""Initial migration

Revision ID: 4b2f9d79c93c
Revises:
Create Date: 2026-01-10 13:33:22.409788

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b2f9d79c93c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cost_aggregates",
        sa.Column("id", toolkit_extensions.database.models.UUIDType(), nullable=False),
        sa.Column("dimension_type", sa.String(length=50), nullable=False),
        sa.Column("dimension_id", sa.String(length=255), nullable=False),
        sa.Column("period_type", sa.String(length=50), nullable=False),
        sa.Column("period_start", sa.DateTime(), nullable=False),
        sa.Column("period_end", sa.DateTime(), nullable=False),
        sa.Column("total_requests", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("total_cost", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("avg_latency_ms", sa.Integer(), nullable=True),
        sa.Column("cache_hit_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("error_rate", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("computed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_aggregates_unique",
        "cost_aggregates",
        ["dimension_type", "dimension_id", "period_type", "period_start"],
        unique=True,
    )
    op.create_index(
        op.f("ix_cost_aggregates_dimension_id"), "cost_aggregates", ["dimension_id"], unique=False
    )
    op.create_index(
        op.f("ix_cost_aggregates_dimension_type"),
        "cost_aggregates",
        ["dimension_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_cost_aggregates_period_start"), "cost_aggregates", ["period_start"], unique=False
    )
    op.create_index(
        op.f("ix_cost_aggregates_period_type"), "cost_aggregates", ["period_type"], unique=False
    )
    op.create_index(
        op.f("ix_cost_aggregates_total_cost"), "cost_aggregates", ["total_cost"], unique=False
    )
    op.create_table(
        "teams",
        sa.Column("id", toolkit_extensions.database.models.UUIDType(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cost_center", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("extra_metadata", toolkit_extensions.database.models.JSONType(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_teams_cost_center"), "teams", ["cost_center"], unique=False)
    op.create_index(op.f("ix_teams_name"), "teams", ["name"], unique=False)
    op.create_index(op.f("ix_teams_status"), "teams", ["status"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", toolkit_extensions.database.models.UUIDType(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("team_id", toolkit_extensions.database.models.UUIDType(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("extra_metadata", toolkit_extensions.database.models.JSONType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_status"), "users", ["status"], unique=False)
    op.create_index(op.f("ix_users_team_id"), "users", ["team_id"], unique=False)
    op.create_table(
        "api_keys",
        sa.Column("id", toolkit_extensions.database.models.UUIDType(), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("key_prefix", sa.String(length=20), nullable=True),
        sa.Column("user_id", toolkit_extensions.database.models.UUIDType(), nullable=True),
        sa.Column("team_id", toolkit_extensions.database.models.UUIDType(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("scopes", toolkit_extensions.database.models.JSONType(), nullable=True),
        sa.Column("rate_limit_rpm", sa.Integer(), nullable=True),
        sa.Column("rate_limit_tpm", sa.Integer(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("extra_metadata", toolkit_extensions.database.models.JSONType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_expires_at"), "api_keys", ["expires_at"], unique=False)
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_index(op.f("ix_api_keys_status"), "api_keys", ["status"], unique=False)
    op.create_index(op.f("ix_api_keys_user_id"), "api_keys", ["user_id"], unique=False)
    op.create_table(
        "projects",
        sa.Column("id", toolkit_extensions.database.models.UUIDType(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("team_id", toolkit_extensions.database.models.UUIDType(), nullable=True),
        sa.Column("owner_id", toolkit_extensions.database.models.UUIDType(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("extra_metadata", toolkit_extensions.database.models.JSONType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_projects_name"), "projects", ["name"], unique=False)
    op.create_index(op.f("ix_projects_owner_id"), "projects", ["owner_id"], unique=False)
    op.create_index(op.f("ix_projects_team_id"), "projects", ["team_id"], unique=False)
    op.create_table(
        "budgets",
        sa.Column("id", toolkit_extensions.database.models.UUIDType(), nullable=False),
        sa.Column("user_id", toolkit_extensions.database.models.UUIDType(), nullable=True),
        sa.Column("team_id", toolkit_extensions.database.models.UUIDType(), nullable=True),
        sa.Column("project_id", toolkit_extensions.database.models.UUIDType(), nullable=True),
        sa.Column("period", sa.String(length=50), nullable=False),
        sa.Column("limit_amount", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("alert_threshold", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("extra_metadata", toolkit_extensions.database.models.JSONType(), nullable=True),
        sa.CheckConstraint(
            "\n            (user_id IS NOT NULL AND team_id IS NULL AND project_id IS NULL) OR\n            (user_id IS NULL AND team_id IS NOT NULL AND project_id IS NULL) OR\n            (user_id IS NULL AND team_id IS NULL AND project_id IS NOT NULL)\n            ",
            name="budget_attribution_check",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_budgets_enabled"), "budgets", ["enabled"], unique=False)
    op.create_index(op.f("ix_budgets_period"), "budgets", ["period"], unique=False)
    op.create_index(op.f("ix_budgets_project_id"), "budgets", ["project_id"], unique=False)
    op.create_index(op.f("ix_budgets_team_id"), "budgets", ["team_id"], unique=False)
    op.create_index(op.f("ix_budgets_user_id"), "budgets", ["user_id"], unique=False)
    op.create_table(
        "llm_requests",
        sa.Column("id", toolkit_extensions.database.models.UUIDType(), nullable=False),
        sa.Column("request_id", sa.String(length=255), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.Column("user_id", toolkit_extensions.database.models.UUIDType(), nullable=True),
        sa.Column("team_id", toolkit_extensions.database.models.UUIDType(), nullable=True),
        sa.Column("project_id", toolkit_extensions.database.models.UUIDType(), nullable=True),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("prompt_cost", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("completion_cost", sa.Numeric(precision=10, scale=6), nullable=True),
        sa.Column("total_cost", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("cache_hit", sa.Boolean(), nullable=True),
        sa.Column("status", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("extra_metadata", toolkit_extensions.database.models.JSONType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["team_id"],
            ["teams.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_llm_requests_model"), "llm_requests", ["model"], unique=False)
    op.create_index(
        op.f("ix_llm_requests_project_id"), "llm_requests", ["project_id"], unique=False
    )
    op.create_index(op.f("ix_llm_requests_provider"), "llm_requests", ["provider"], unique=False)
    op.create_index(op.f("ix_llm_requests_status"), "llm_requests", ["status"], unique=False)
    op.create_index(op.f("ix_llm_requests_team_id"), "llm_requests", ["team_id"], unique=False)
    op.create_index(op.f("ix_llm_requests_timestamp"), "llm_requests", ["timestamp"], unique=False)
    op.create_index(
        op.f("ix_llm_requests_total_cost"), "llm_requests", ["total_cost"], unique=False
    )
    op.create_index(op.f("ix_llm_requests_user_id"), "llm_requests", ["user_id"], unique=False)
    op.create_table(
        "budget_alerts",
        sa.Column("id", toolkit_extensions.database.models.UUIDType(), nullable=False),
        sa.Column("budget_id", toolkit_extensions.database.models.UUIDType(), nullable=False),
        sa.Column("alert_type", sa.String(length=50), nullable=False),
        sa.Column("current_spend", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("budget_limit", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("percentage_used", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("notified_at", sa.DateTime(), nullable=True),
        sa.Column("notification_sent", sa.Boolean(), nullable=True),
        sa.Column(
            "notification_channels", toolkit_extensions.database.models.JSONType(), nullable=True
        ),
        sa.Column("extra_metadata", toolkit_extensions.database.models.JSONType(), nullable=True),
        sa.ForeignKeyConstraint(
            ["budget_id"],
            ["budgets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_budget_alerts_alert_type"), "budget_alerts", ["alert_type"], unique=False
    )
    op.create_index(
        op.f("ix_budget_alerts_budget_id"), "budget_alerts", ["budget_id"], unique=False
    )
    op.create_index(
        op.f("ix_budget_alerts_notified_at"), "budget_alerts", ["notified_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_budget_alerts_notified_at"), table_name="budget_alerts")
    op.drop_index(op.f("ix_budget_alerts_budget_id"), table_name="budget_alerts")
    op.drop_index(op.f("ix_budget_alerts_alert_type"), table_name="budget_alerts")
    op.drop_table("budget_alerts")
    op.drop_index(op.f("ix_llm_requests_user_id"), table_name="llm_requests")
    op.drop_index(op.f("ix_llm_requests_total_cost"), table_name="llm_requests")
    op.drop_index(op.f("ix_llm_requests_timestamp"), table_name="llm_requests")
    op.drop_index(op.f("ix_llm_requests_team_id"), table_name="llm_requests")
    op.drop_index(op.f("ix_llm_requests_status"), table_name="llm_requests")
    op.drop_index(op.f("ix_llm_requests_provider"), table_name="llm_requests")
    op.drop_index(op.f("ix_llm_requests_project_id"), table_name="llm_requests")
    op.drop_index(op.f("ix_llm_requests_model"), table_name="llm_requests")
    op.drop_table("llm_requests")
    op.drop_index(op.f("ix_budgets_user_id"), table_name="budgets")
    op.drop_index(op.f("ix_budgets_team_id"), table_name="budgets")
    op.drop_index(op.f("ix_budgets_project_id"), table_name="budgets")
    op.drop_index(op.f("ix_budgets_period"), table_name="budgets")
    op.drop_index(op.f("ix_budgets_enabled"), table_name="budgets")
    op.drop_table("budgets")
    op.drop_index(op.f("ix_projects_team_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_owner_id"), table_name="projects")
    op.drop_index(op.f("ix_projects_name"), table_name="projects")
    op.drop_table("projects")
    op.drop_index(op.f("ix_api_keys_user_id"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_status"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_index(op.f("ix_api_keys_expires_at"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_index(op.f("ix_users_team_id"), table_name="users")
    op.drop_index(op.f("ix_users_status"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_teams_status"), table_name="teams")
    op.drop_index(op.f("ix_teams_name"), table_name="teams")
    op.drop_index(op.f("ix_teams_cost_center"), table_name="teams")
    op.drop_table("teams")
    op.drop_index(op.f("ix_cost_aggregates_total_cost"), table_name="cost_aggregates")
    op.drop_index(op.f("ix_cost_aggregates_period_type"), table_name="cost_aggregates")
    op.drop_index(op.f("ix_cost_aggregates_period_start"), table_name="cost_aggregates")
    op.drop_index(op.f("ix_cost_aggregates_dimension_type"), table_name="cost_aggregates")
    op.drop_index(op.f("ix_cost_aggregates_dimension_id"), table_name="cost_aggregates")
    op.drop_index("idx_aggregates_unique", table_name="cost_aggregates")
    op.drop_table("cost_aggregates")
    # ### end Alembic commands ###
